eureka:
  client:
    healthcheck:
      enabled: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  security:
    user:
      name: xfreng
      password: passw0rd
  rabbitmq:
    host: 192.168.131.150
    port: 5672
    username: ${spring.security.user.name}
    password: ${spring.security.user.password}
info:
  version: "@project.version@"
logging:
  config: classpath:conf/log4j2.xml