spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  security:
    user:
      name: xfreng
      password: passw0rd
info:
  version: "@project.version@"