package com.fui.cloud.model.fui;

import com.fui.cloud.model.BaseModel;

public class DictType extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_dict_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_dict_type.dict_code
     *
     * @mbggenerated
     */
    private String dictCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_dict_type.dict_desc
     *
     * @mbggenerated
     */
    private String dictDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_dict_type.id
     *
     * @return the value of fui_dict_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_dict_type.id
     *
     * @param id the value for fui_dict_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_dict_type.dict_code
     *
     * @return the value of fui_dict_type.dict_code
     *
     * @mbggenerated
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_dict_type.dict_code
     *
     * @param dictCode the value for fui_dict_type.dict_code
     *
     * @mbggenerated
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_dict_type.dict_desc
     *
     * @return the value of fui_dict_type.dict_desc
     *
     * @mbggenerated
     */
    public String getDictDesc() {
        return dictDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_dict_type.dict_desc
     *
     * @param dictDesc the value for fui_dict_type.dict_desc
     *
     * @mbggenerated
     */
    public void setDictDesc(String dictDesc) {
        this.dictDesc = dictDesc == null ? null : dictDesc.trim();
    }
}