package com.fui.cloud.model.fui;

import com.fui.cloud.model.BaseModel;

public class DictEntry extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_dict_entry.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_dict_entry.dict_code
     *
     * @mbggenerated
     */
    private String dictCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_dict_entry.dict_entry_code
     *
     * @mbggenerated
     */
    private String dictEntryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_dict_entry.dict_entry_desc
     *
     * @mbggenerated
     */
    private String dictEntryDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_dict_entry.dict_entry_sort
     *
     * @mbggenerated
     */
    private Long dictEntrySort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_dict_entry.id
     *
     * @return the value of fui_dict_entry.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_dict_entry.id
     *
     * @param id the value for fui_dict_entry.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_dict_entry.dict_code
     *
     * @return the value of fui_dict_entry.dict_code
     *
     * @mbggenerated
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_dict_entry.dict_code
     *
     * @param dictCode the value for fui_dict_entry.dict_code
     *
     * @mbggenerated
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_dict_entry.dict_entry_code
     *
     * @return the value of fui_dict_entry.dict_entry_code
     *
     * @mbggenerated
     */
    public String getDictEntryCode() {
        return dictEntryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_dict_entry.dict_entry_code
     *
     * @param dictEntryCode the value for fui_dict_entry.dict_entry_code
     *
     * @mbggenerated
     */
    public void setDictEntryCode(String dictEntryCode) {
        this.dictEntryCode = dictEntryCode == null ? null : dictEntryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_dict_entry.dict_entry_desc
     *
     * @return the value of fui_dict_entry.dict_entry_desc
     *
     * @mbggenerated
     */
    public String getDictEntryDesc() {
        return dictEntryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_dict_entry.dict_entry_desc
     *
     * @param dictEntryDesc the value for fui_dict_entry.dict_entry_desc
     *
     * @mbggenerated
     */
    public void setDictEntryDesc(String dictEntryDesc) {
        this.dictEntryDesc = dictEntryDesc == null ? null : dictEntryDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_dict_entry.dict_entry_sort
     *
     * @return the value of fui_dict_entry.dict_entry_sort
     *
     * @mbggenerated
     */
    public Long getDictEntrySort() {
        return dictEntrySort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_dict_entry.dict_entry_sort
     *
     * @param dictEntrySort the value for fui_dict_entry.dict_entry_sort
     *
     * @mbggenerated
     */
    public void setDictEntrySort(Long dictEntrySort) {
        this.dictEntrySort = dictEntrySort;
    }
}