package com.fui.cloud.model.fui;

import com.fui.cloud.model.BaseModel;

import java.util.Date;

public class Leave extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_oa_leave.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_oa_leave.apply_time
     *
     * @mbggenerated
     */
    private Date applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_oa_leave.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_oa_leave.leave_type
     *
     * @mbggenerated
     */
    private String leaveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_oa_leave.process_instance_id
     *
     * @mbggenerated
     */
    private String processInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_oa_leave.reality_end_time
     *
     * @mbggenerated
     */
    private Date realityEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_oa_leave.reality_start_time
     *
     * @mbggenerated
     */
    private Date realityStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_oa_leave.reason
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_oa_leave.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_oa_leave.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_oa_leave.id
     *
     * @return the value of fui_oa_leave.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_oa_leave.id
     *
     * @param id the value for fui_oa_leave.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_oa_leave.apply_time
     *
     * @return the value of fui_oa_leave.apply_time
     * @mbggenerated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_oa_leave.apply_time
     *
     * @param applyTime the value for fui_oa_leave.apply_time
     * @mbggenerated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_oa_leave.end_time
     *
     * @return the value of fui_oa_leave.end_time
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_oa_leave.end_time
     *
     * @param endTime the value for fui_oa_leave.end_time
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_oa_leave.leave_type
     *
     * @return the value of fui_oa_leave.leave_type
     * @mbggenerated
     */
    public String getLeaveType() {
        return leaveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_oa_leave.leave_type
     *
     * @param leaveType the value for fui_oa_leave.leave_type
     * @mbggenerated
     */
    public void setLeaveType(String leaveType) {
        this.leaveType = leaveType == null ? null : leaveType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_oa_leave.process_instance_id
     *
     * @return the value of fui_oa_leave.process_instance_id
     * @mbggenerated
     */
    public String getProcessInstanceId() {
        return processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_oa_leave.process_instance_id
     *
     * @param processInstanceId the value for fui_oa_leave.process_instance_id
     * @mbggenerated
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId == null ? null : processInstanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_oa_leave.reality_end_time
     *
     * @return the value of fui_oa_leave.reality_end_time
     * @mbggenerated
     */
    public Date getRealityEndTime() {
        return realityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_oa_leave.reality_end_time
     *
     * @param realityEndTime the value for fui_oa_leave.reality_end_time
     * @mbggenerated
     */
    public void setRealityEndTime(Date realityEndTime) {
        this.realityEndTime = realityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_oa_leave.reality_start_time
     *
     * @return the value of fui_oa_leave.reality_start_time
     * @mbggenerated
     */
    public Date getRealityStartTime() {
        return realityStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_oa_leave.reality_start_time
     *
     * @param realityStartTime the value for fui_oa_leave.reality_start_time
     * @mbggenerated
     */
    public void setRealityStartTime(Date realityStartTime) {
        this.realityStartTime = realityStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_oa_leave.reason
     *
     * @return the value of fui_oa_leave.reason
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_oa_leave.reason
     *
     * @param reason the value for fui_oa_leave.reason
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_oa_leave.start_time
     *
     * @return the value of fui_oa_leave.start_time
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_oa_leave.start_time
     *
     * @param startTime the value for fui_oa_leave.start_time
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_oa_leave.user_id
     *
     * @return the value of fui_oa_leave.user_id
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_oa_leave.user_id
     *
     * @param userId the value for fui_oa_leave.user_id
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}