package com.fui.cloud.model.fui;

import com.fui.cloud.model.BaseModel;

public class MenuShortcut extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_menu_shortcut.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_menu_shortcut.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_menu_shortcut.menu_id
     *
     * @mbggenerated
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_menu_shortcut.order_no
     *
     * @mbggenerated
     */
    private Integer orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_menu_shortcut.menu_image_path
     *
     * @mbggenerated
     */
    private String menuImagePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_menu_shortcut.id
     *
     * @return the value of fui_menu_shortcut.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_menu_shortcut.id
     *
     * @param id the value for fui_menu_shortcut.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_menu_shortcut.user_id
     *
     * @return the value of fui_menu_shortcut.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_menu_shortcut.user_id
     *
     * @param userId the value for fui_menu_shortcut.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_menu_shortcut.menu_id
     *
     * @return the value of fui_menu_shortcut.menu_id
     *
     * @mbggenerated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_menu_shortcut.menu_id
     *
     * @param menuId the value for fui_menu_shortcut.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_menu_shortcut.order_no
     *
     * @return the value of fui_menu_shortcut.order_no
     *
     * @mbggenerated
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_menu_shortcut.order_no
     *
     * @param orderNo the value for fui_menu_shortcut.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_menu_shortcut.menu_image_path
     *
     * @return the value of fui_menu_shortcut.menu_image_path
     *
     * @mbggenerated
     */
    public String getMenuImagePath() {
        return menuImagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_menu_shortcut.menu_image_path
     *
     * @param menuImagePath the value for fui_menu_shortcut.menu_image_path
     *
     * @mbggenerated
     */
    public void setMenuImagePath(String menuImagePath) {
        this.menuImagePath = menuImagePath == null ? null : menuImagePath.trim();
    }
}