package com.fui.cloud.model.fui;

import com.fui.cloud.model.BaseModel;

public class Permissions extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_permissions.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_permissions.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_permissions.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_permissions.text
     *
     * @mbggenerated
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_permissions.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_permissions.node_type
     *
     * @mbggenerated
     */
    private String nodeType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_permissions.id
     *
     * @return the value of fui_permissions.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_permissions.id
     *
     * @param id the value for fui_permissions.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_permissions.parent_id
     *
     * @return the value of fui_permissions.parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_permissions.parent_id
     *
     * @param parentId the value for fui_permissions.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_permissions.code
     *
     * @return the value of fui_permissions.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_permissions.code
     *
     * @param code the value for fui_permissions.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_permissions.text
     *
     * @return the value of fui_permissions.text
     *
     * @mbggenerated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_permissions.text
     *
     * @param text the value for fui_permissions.text
     *
     * @mbggenerated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_permissions.url
     *
     * @return the value of fui_permissions.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_permissions.url
     *
     * @param url the value for fui_permissions.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_permissions.node_type
     *
     * @return the value of fui_permissions.node_type
     *
     * @mbggenerated
     */
    public String getNodeType() {
        return nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_permissions.node_type
     *
     * @param nodeType the value for fui_permissions.node_type
     *
     * @mbggenerated
     */
    public void setNodeType(String nodeType) {
        this.nodeType = nodeType == null ? null : nodeType.trim();
    }
}