package com.fui.cloud.model.fui;

import com.fui.cloud.model.BaseModel;

public class Roles extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_roles.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_roles.role_code
     *
     * @mbggenerated
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_roles.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_roles.permissions
     *
     * @mbggenerated
     */
    private String permissions;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_roles.id
     *
     * @return the value of fui_roles.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_roles.id
     *
     * @param id the value for fui_roles.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_roles.role_code
     *
     * @return the value of fui_roles.role_code
     *
     * @mbggenerated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_roles.role_code
     *
     * @param roleCode the value for fui_roles.role_code
     *
     * @mbggenerated
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_roles.role_name
     *
     * @return the value of fui_roles.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_roles.role_name
     *
     * @param roleName the value for fui_roles.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_roles.permissions
     *
     * @return the value of fui_roles.permissions
     *
     * @mbggenerated
     */
    public String getPermissions() {
        return permissions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_roles.permissions
     *
     * @param permissions the value for fui_roles.permissions
     *
     * @mbggenerated
     */
    public void setPermissions(String permissions) {
        this.permissions = permissions == null ? null : permissions.trim();
    }
}