package com.fui.cloud.model.fui;

import com.fui.cloud.model.BaseModel;

public class RolePermissions extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_role_permissions.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_role_permissions.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_role_permissions.permission_id
     *
     * @mbggenerated
     */
    private Long permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_role_permissions.id
     *
     * @return the value of fui_role_permissions.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_role_permissions.id
     *
     * @param id the value for fui_role_permissions.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_role_permissions.role_id
     *
     * @return the value of fui_role_permissions.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_role_permissions.role_id
     *
     * @param roleId the value for fui_role_permissions.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_role_permissions.permission_id
     *
     * @return the value of fui_role_permissions.permission_id
     *
     * @mbggenerated
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_role_permissions.permission_id
     *
     * @param permissionId the value for fui_role_permissions.permission_id
     *
     * @mbggenerated
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }
}