package com.fui.cloud.model.fui;

import com.fui.cloud.model.BaseModel;
import java.util.Date;

public class User extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_user.ename
     *
     * @mbggenerated
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_user.cname
     *
     * @mbggenerated
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_user.style
     *
     * @mbggenerated
     */
    private String style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_user.menu_type
     *
     * @mbggenerated
     */
    private String menuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_user.erased
     *
     * @mbggenerated
     */
    private Boolean erased;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_user.login_count
     *
     * @mbggenerated
     */
    private Long loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_user.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_user.id
     *
     * @return the value of fui_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_user.id
     *
     * @param id the value for fui_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_user.ename
     *
     * @return the value of fui_user.ename
     *
     * @mbggenerated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_user.ename
     *
     * @param ename the value for fui_user.ename
     *
     * @mbggenerated
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_user.cname
     *
     * @return the value of fui_user.cname
     *
     * @mbggenerated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_user.cname
     *
     * @param cname the value for fui_user.cname
     *
     * @mbggenerated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_user.password
     *
     * @return the value of fui_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_user.password
     *
     * @param password the value for fui_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_user.style
     *
     * @return the value of fui_user.style
     *
     * @mbggenerated
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_user.style
     *
     * @param style the value for fui_user.style
     *
     * @mbggenerated
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_user.menu_type
     *
     * @return the value of fui_user.menu_type
     *
     * @mbggenerated
     */
    public String getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_user.menu_type
     *
     * @param menuType the value for fui_user.menu_type
     *
     * @mbggenerated
     */
    public void setMenuType(String menuType) {
        this.menuType = menuType == null ? null : menuType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_user.erased
     *
     * @return the value of fui_user.erased
     *
     * @mbggenerated
     */
    public Boolean getErased() {
        return erased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_user.erased
     *
     * @param erased the value for fui_user.erased
     *
     * @mbggenerated
     */
    public void setErased(Boolean erased) {
        this.erased = erased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_user.login_count
     *
     * @return the value of fui_user.login_count
     *
     * @mbggenerated
     */
    public Long getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_user.login_count
     *
     * @param loginCount the value for fui_user.login_count
     *
     * @mbggenerated
     */
    public void setLoginCount(Long loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_user.last_login_time
     *
     * @return the value of fui_user.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_user.last_login_time
     *
     * @param lastLoginTime the value for fui_user.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_user.create_time
     *
     * @return the value of fui_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_user.create_time
     *
     * @param createTime the value for fui_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}