package com.fui.cloud.model.fui;

import com.fui.cloud.model.BaseModel;

public class UserOrganizations extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_user_organizations.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_user_organizations.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fui_user_organizations.organization_id
     *
     * @mbggenerated
     */
    private Long organizationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_user_organizations.id
     *
     * @return the value of fui_user_organizations.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_user_organizations.id
     *
     * @param id the value for fui_user_organizations.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_user_organizations.user_id
     *
     * @return the value of fui_user_organizations.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_user_organizations.user_id
     *
     * @param userId the value for fui_user_organizations.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fui_user_organizations.organization_id
     *
     * @return the value of fui_user_organizations.organization_id
     *
     * @mbggenerated
     */
    public Long getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fui_user_organizations.organization_id
     *
     * @param organizationId the value for fui_user_organizations.organization_id
     *
     * @mbggenerated
     */
    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }
}