eureka:
  client:
    healthcheck:
      enabled: true
spring:
  security:
    user:
      name: xfreng
      password: passw0rd
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  aop:
    proxy-target-class: true
info:
  version: "@project.version@"
fui:
  quartz:
    quartzSwitch: false
    cronExpression: 0/2 * * * * ?