#服务注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    appname: cloud-service

server:
  port: 8072

spring:
  application:
    name: cloud-service