spring:
  application:
    name: fui-db-sql
  profiles:
    active: consul
#    active: dev
  security:
    user:
      name: xfreng
      password: passw0rd
info:
  version: @project.version@
logging:
  config: classpath:conf/log4j2.xml