eureka:
  client:
    healthcheck:
      enabled: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  rabbitmq:
    host: 192.168.131.150
    port: 5672
    username: ${security.user.name}
    password: ${security.user.password}
info:
  version: @project.version@
management:
  security:
    enabled: false
security:
  user:
    name: xfreng
    password: passw0rd
logging:
  config: classpath:conf/logback.xml
  level: debug