spring:
  cloud:
    #配置consul服务注册中心
    consul:
      host: 192.168.131.150
      port: 8500
      enabled: true
      discovery:
        enabled: true
        prefer-ip-address: true
logging:
  file: /usr/apps/logs/cas-admin.log