#服务注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/
  instance:
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 1
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 5
server:
  port: 8889
logging:
  file: D:/installed/apache-tomcat-7.0.72/logs/boot-admin-server.log