spring:
  application:
    name: config-server
  profiles:
    active: dev
info:
  version: @project.version@
management:
  security:
    enabled: false
security:
  user:
    name: xfreng
    password: passw0rd
logging:
  config: classpath:conf/logback.xml
  level: debug
