#服务端口
server:
  port: 8082
#服务注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/
  instance:
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 1
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 5
#spring设置
spring:
  cloud:
    config:
      enabled: true
      server:
        svn:
          uri: https://192.168.131.150/svn/repos/cloud-fui-config-repo
          username: xiongshifeng
          password: xiongshifeng
        default-label: config
    bus:
      enabled: true
  rabbitmq:
    host: 192.168.131.150
    port: 5672
    username: ${security.user.name}
    password: ${security.user.password}
logging:
  file: D:/installed/apache-tomcat-7.0.72/logs/fui-config.log