spring:
  application:
    name: config-server
  profiles:
    active: dev
    #active: consul
  security:
    user:
      name: xfreng
      password: passw0rd
info:
  version: "@project.version@"
logging:
  config: classpath:conf/logback.xml