#服务端口
server:
  port: 8082
#服务注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
  instance:
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 1
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 5
#spring设置
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xfreng/spring-cloud-microservice.git
          searchPaths: cloud-fui-config-repo
    bus:
      enabled: true
  rabbitmq:
    host: 192.168.131.150
    port: 5672
    username: ${spring.security.user.name}
    password: ${spring.security.user.password}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: D:/installed/apache-tomcat-7.0.72/logs/fui-config.log